#######################################################
# This file was auto-generated by elixir_bindings.zig #
#              Do not manually modify.                #
#######################################################

defmodule TigerBeetlex.AccountFilter do
  @moduledoc """
  See [AccountFilter](https://docs.tigerbeetle.com/reference/account-filter#).
  """
  defstruct [
    :account_id,
    :timestamp_min,
    :timestamp_max,
    :limit,
    :flags
  ]
end
