#######################################################
# This file was auto-generated by elixir_bindings.zig #
#              Do not manually modify.                #
#######################################################

defmodule TigerBeetlex.AccountFilter do
  @moduledoc """
  See [AccountFilter](https://docs.tigerbeetle.com/reference/account-filter#).
  """
  defstruct [
    :account_id,
    :user_data_128,
    :user_data_64,
    :user_data_32,
    :code,
    :timestamp_min,
    :timestamp_max,
    :limit,
    :flags
  ]
end
