#######################################################
# This file was auto-generated by elixir_bindings.zig #
#              Do not manually modify.                #
#######################################################

defmodule TigerBeetlex.Account do
  @moduledoc """
  See [Account](https://docs.tigerbeetle.com/reference/account#).
  """
  defstruct [
    :id,
    :debits_pending,
    :debits_posted,
    :credits_pending,
    :credits_posted,
    :user_data_128,
    :user_data_64,
    :user_data_32,
    :reserved,
    :ledger,
    :code,
    :flags,
    :timestamp
  ]
end
