#######################################################
# This file was auto-generated by elixir_bindings.zig #
#              Do not manually modify.                #
#######################################################

defmodule TigerBeetlex.AccountBalance do
  @moduledoc """
  See [AccountBalance](https://docs.tigerbeetle.com/reference/account-balances#).
  """
  defstruct [
    :debits_pending,
    :debits_posted,
    :credits_pending,
    :credits_posted,
    :timestamp
  ]
end
