#######################################################
# This file was auto-generated by elixir_bindings.zig #
#              Do not manually modify.                #
#######################################################

defmodule TigerBeetlex.QueryFilter do
  @moduledoc """
  See [QueryFilter](https://docs.tigerbeetle.com/reference/query-filter#).
  """
  defstruct [
    :user_data_128,
    :user_data_64,
    :user_data_32,
    :ledger,
    :code,
    :timestamp_min,
    :timestamp_max,
    :limit,
    :flags
  ]
end
