#######################################################
# This file was auto-generated by elixir_bindings.zig #
#              Do not manually modify.                #
#######################################################

defmodule TigerBeetlex.TransferFlags do
  import Bitwise

  @moduledoc """
  See [TransferFlags](https://docs.tigerbeetle.com/reference/transfer#flags).
  """

  @doc """
  See [linked](https://docs.tigerbeetle.com/reference/transfer#flagslinked).
  """
  def linked(current \\ 0) do
    current ||| 1 <<< 0
  end

  @doc """
  See [pending](https://docs.tigerbeetle.com/reference/transfer#flagspending).
  """
  def pending(current \\ 0) do
    current ||| 1 <<< 1
  end

  @doc """
  See [post_pending_transfer](https://docs.tigerbeetle.com/reference/transfer#flagspost_pending_transfer).
  """
  def post_pending_transfer(current \\ 0) do
    current ||| 1 <<< 2
  end

  @doc """
  See [void_pending_transfer](https://docs.tigerbeetle.com/reference/transfer#flagsvoid_pending_transfer).
  """
  def void_pending_transfer(current \\ 0) do
    current ||| 1 <<< 3
  end

  @doc """
  See [balancing_debit](https://docs.tigerbeetle.com/reference/transfer#flagsbalancing_debit).
  """
  def balancing_debit(current \\ 0) do
    current ||| 1 <<< 4
  end

  @doc """
  See [balancing_credit](https://docs.tigerbeetle.com/reference/transfer#flagsbalancing_credit).
  """
  def balancing_credit(current \\ 0) do
    current ||| 1 <<< 5
  end
end
