#######################################################
# This file was auto-generated by elixir_bindings.zig #
#              Do not manually modify.                #
#######################################################

defmodule TigerBeetlex.Transfer do
  @moduledoc """
  See [Transfer](https://docs.tigerbeetle.com/reference/transfer#).
  """
  defstruct [
    :id,
    :debit_account_id,
    :credit_account_id,
    :amount,
    :pending_id,
    :user_data_128,
    :user_data_64,
    :user_data_32,
    :timeout,
    :ledger,
    :code,
    :flags,
    :timestamp
  ]
end
